title: Miss Wish
slug: miss-wish
course: doa
description: A description of the Miss Wish class
content:
  -
    title: Introduction
    description: TBC
    slug: intro
    type: content
    rich: true
  -
    title: Further Reading
    description: TBC
    slug: reading
    type: content
    rich: true
  -
    title: Extended Content
    description: TBC
    slug: extended
    type: content
    rich: true
  -
    title: Homework
    description: TBC
    slug: homework
    type: homework