title: Self-Portraits
description: A description of the Self-Portraits class
slug: self-portraits
course: doa
content:
  -
    title: Introduction
    description: >-
      Photographer Graham Macindoe and journalist Susan Stellin provide a case-study for us to consider how images are interpreted and to reflect on their enduring and potentially evolving impact.
      @[bio](Graham Macindoe|CDN_URL/images/Graham_cropped.jpg|Graham Macindoe is a New York based photographer and an adjunct professor at Parsons The New School. His work has been widely published in the UK and the US.|https://twitter.com/grahammacindoe)
    slug: intro
    type: content
    rich: true
  -
    title: Live Class
    description: Join the live discussion and share your thoughts via Twitter. All images are copyright Graham Macindoe.
    slug: liveclass
    type: liveclass
    duration: 1663.1
    transcript: self-portraits-transcript
    images: self-portraits-images
    intro: 
      title: Listen to the class introduction
      audio: https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-self-portraits-intro-64.mp3
    audio:
      - https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-self-portraits-main-64.mp3
      - https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-self-portraits-main-64.webm
  -
    title: Further Reading
    description: >-
      Here you’ll find links to articles relating to the work discussed and some of the themes discussed.
      Please tweet any of your suggestions for links @Jonathan_Worth
    slug: reading
    type: content
    rich: true
  -
    title: Extended Content
    description: Access Graham and Susan’s original full-length interviews and extra related content.
    video: Renqf1Ltg04
    slug: extended
    type: content
    rich: true