hashtag: "#rocket
starts: "2017-04-01T22:47:31-07:00"
ends: "2018-09-20T22:47:31-07:00"
accounts: 
  - edjenkins91
langs:
  - en
about: about.md
info: info.md
slug: rocket
classes:
  -
    dir: class1
    slug: evidence
    content:
      -
        url: intro.md
        slug: intro
      -
        url: prework.md
        slug: prework
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2018-04-02T10:57:37+01:00"
            leadhub: true
            hub_id: "ncl"
      -
        url: deepdive.md
        slug: deepdive
      -
        url: whatnext.md
        slug: whatnext