hashtag: "#rocket"
starts: "2018-02-01T22:47:31-07:00"
ends: "2018-09-20T22:47:31-07:00"
accounts: 
  - edjenkins91
langs:
  - en
about: about.md
info: info.md
slug: rocket
classes:
  -
    dir: self-portraits
    slug: self-portraits
    content:
      -
        url: intro.md
        slug: intro
      -
        url: homework.md
        slug: homework
      -
        url: class.md
        slug: liveclass
      -
        url: fourcorners.md
        slug: fourcorners
      -
        url: deepdive.md
        slug: deepdive
      -
        url: extended.md
        slug: extended
  -
    dir: kensington-blues
    slug: kensington-blues
    content:
      -
        url: intro.md
        slug: intro
      -
        url: class.md
        slug: liveclass
      -
        url: fourcorners.md
        slug: fourcorners
      -
        url: extended.md
        slug: extended
  -
    dir: miss-wish
    slug: miss-wish
    content:
      -
        url: intro.md
        slug: intro
      -
        url: class.md
        slug: liveclass
      -
        url: fourcorners.md
        slug: fourcorners
      -
        url: extended.md
        slug: extended
