hashtag: "#yourcoursehashtag"
starts: "2017-04-01T22:47:31-07:00"
ends: "2018-09-20T22:47:31-07:00"
accounts: 
  - <yourcoursetwitteraccount>
langs:
  - en
about: about.md
info: info.md
slug: talkingpictures
classes:
  -
    dir: class1
    slug: evidence
    content:
      -
        url: intro.md
        slug: intro
      -
        url: fourcorners.md
        slug: fourcorners
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: prework.md
        slug: prework
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2018-04-02T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        url: deepdive.md
        slug: deepdive
      -
        url: extended.md
        slug: extended
      -
        url: postwork.md
        slug: postwork
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2018-04-08T22:57:37-07:00"
      -
        url: whatnext.md
        slug: whatnext