title: Kensington Blues
slug: kensington-blues
course: doa
description: A description of the Kensington Blues class
content:
  -
    title: Introduction
    description: >-
      In this, the second of three episodes, new participants revisit some of the themes of episode one and their alternate perspectives enable us to build on those discussions. We move from the self-portraiture of Graham Macindoe, to the participatory practices of Jeffery Stockbridge and his Kensington Blues project.
      @[bio](Jeffrey Stockbridge|default|Graduated from Drexel University with a BS in Photography in 2005. His photographs have been included in recent exhibitions at The National Portrait Gallery London, The Philadelphia Museum of Art, The Delaware Art Museum, The Delaware Center for Contemporary Arts, The Houston Center for Photography, The Wapping Project Bankside and The Print Center. Stockbridge lives and works in Philadelphia, Pennsylvania.|http://www.jeffreystockbridge.com/)
    slug: intro
    type: content
    rich: true
  -
    title: Live Class
    description: Join the live discussion. All images displayed are Copyrighted - All Rights Reserved.
    slug: liveclass
    type: liveclass
    duration: 1554
    transcript: kensington-blues-transcript
    # images: kensington-blues-images
    intros:
      -
        title: Jonathan Worth's Introduction
        audio: https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-kensington-blues-intro-64.mp3
    audio:
      - https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-kensington-blues-main-64.mp3
      - https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-kensington-blues-main-64.webm
  -
    title: Further Reading
    description: We have curated an extensive list of articles around the topic of Kensington Blues and encourage you to explore the conversations happening across the web. If you find something you think belongs on this list reach out to us.
    slug: reading
    type: content
    rich: true