title: Kensington Blues
slug: kensington-blues
course: doa
description: A description of the Kensington Blues class
content:
  -
    title: Introduction
    description: Photographer Jeffrey Stockbridge discusses photography with others @[bio](Carl Hart|CDN_URL/images/carl_hart.jpg|Carl Hart is the Chair of the Department of Psychology at Columbia University. He is also the Dirk Ziff Professorof Psychology in the Departments of Psychology and Psychiatry. Prof. Hart has published nearly 100 scientificarticles in the area of neuropsychopharmacology and is co-author of the textbook Drugs, Society and Human Behavior (with Charles Ksir).”|http://drcarlhart.com)
    slug: intro
    type: content
    rich: true
  -
    title: Live Class
    description: Join the live discussion. All images displayed are Copyrighted - All Rights Reserved.
    slug: liveclass
    type: liveclass
    duration: 1554
    transcript: kensington-blues-transcript
    images: kensington-blues-images
    # intro: CDN_URL/classes/kensington-blues/kensington-blues-32.mp3
    audio:
      - kensington-blues-32.mp3
      - kensington-blues-32.ogg
  -
    title: Further Reading
    description: We have curated an extensive list of articles around the topic of Kensington Blues and encourage you to explore the conversations happening across the web. If you find something you think belongs on this list reach out to us.
    slug: reading
    type: content
    rich: true
  -
    title: Extended Content
    description: TBC
    slug: extended
    type: content
    rich: true